---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/consultation_requests":
    post:
      summary: создание запроса на консультацию
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patient_id:
                  type: integer
                consultation_request:
                  type: object
                  properties:
                    text:
                      type: string

      responses:
        '201':
          description: Created
  "/drug":
    get:
      summary: Получение названия лекарства с внешнего API
      responses:
        '200':
          description: successful

  "/patients/{patient_id}/recommendations":
    parameters:
      - name: patient_id
        in: path
        description: patient_id
        required: true
        schema:
          type: integer

    get:
      summary: получение списка рекомендаций для конкретного пациента
      responses:
        '200':
          description: successful
  "/consultation_requests/{consultation_request_id}/recommendations":
    parameters:
      - name: consultation_request_id
        in: path
        description: consultation_request_id
        required: true
        schema:
          type: string


    post:
      summary: создание запроса на консультацию
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patient_id:
                  type: integer
                recommendation:
                  type: object
                  properties:
                    text:
                      type: string

      responses:
        '201':
          description: Created
servers:
  - url: http://{defaultHost}
    variables:
      defaultHost:
        default: localhost:3000
