
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%=ENV.fetch("DB_LOGIN") %>
  password: <%=ENV.fetch("DB_PASSWORD") %>
  host: <%=ENV.fetch("DB_HOST") %>

development:
  <<: *default
  database: job_dev

test:
  <<: *default
  database: job_test

production:
  <<: *default
  database: job_prod
